
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 18 14:25:52 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 53;
  public static final int CONST = 7;
  public static final int CASE = 47;
  public static final int NOT_EQUAL = 26;
  public static final int CONTINUE = 41;
  public static final int GREATER = 37;
  public static final int LPAREN = 28;
  public static final int SEMI = 6;
  public static final int LESS = 30;
  public static final int FOR = 8;
  public static final int MINUS = 25;
  public static final int RPAREN = 18;
  public static final int AND = 27;
  public static final int GT_EQU = 39;
  public static final int OR = 42;
  public static final int COMMA = 5;
  public static final int DDOT = 22;
  public static final int CLASS = 14;
  public static final int INC = 36;
  public static final int DIV = 24;
  public static final int ABSTR = 10;
  public static final int PLUS = 17;
  public static final int IF = 21;
  public static final int DOT = 23;
  public static final int SETVAL = 11;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int EQUAL = 29;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MUL = 32;
  public static final int NUMBER = 50;
  public static final int MOD = 31;
  public static final int IDENT = 51;
  public static final int BREAK = 34;
  public static final int KV = 44;
  public static final int VOID = 16;
  public static final int SWITCH = 48;
  public static final int LBRACE = 3;
  public static final int ELSE = 20;
  public static final int LSQUARE = 12;
  public static final int READ = 35;
  public static final int ENUM = 9;
  public static final int WHILE = 46;
  public static final int RSQUARE = 13;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 52;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int QUESTION = 49;
  public static final int DEC = 43;
  public static final int LESS_EQU = 33;
  public static final int DO = 45;
  public static final int PRINT = 38;
}

